name: spotube
description: Open source Spotify client that doesn't require Premium nor uses Electron! Available for both desktop & mobile!

publish_to: "none"

version: 2.7.0+17

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  args: ^2.3.2
  async: ^2.9.0
  audio_service: ^0.18.9
  audio_session: ^0.1.13
  audioplayers: ^3.0.1
  auto_size_text: ^3.0.0
  badges: ^2.0.3
  buttons_tabbar: ^1.3.6
  cached_network_image: ^3.2.2
  catcher:
    git:
      url: https://github.com/ThexXTURBOXx/catcher
  collection: ^1.15.0
  cupertino_icons: ^1.0.5
  curved_navigation_bar: ^1.0.3
  dbus: ^0.7.8
  file_picker: ^5.2.2
  fl_query: ^1.0.0-alpha.2
  fl_query_hooks: ^1.0.0-alpha.2
  fluentui_system_icons: ^1.1.189
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_dotenv: ^5.0.2
  flutter_feather_icons: ^2.0.0+1
  flutter_hooks: ^0.18.2+1
  flutter_inappwebview: ^5.7.2+3
  flutter_riverpod: ^2.1.1
  flutter_svg: ^1.1.6
  fuzzywuzzy: ^0.2.0
  go_router: ^6.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.1.1
  html: ^0.15.1
  http: ^0.13.5
  introduction_screen: ^3.0.2
  json_annotation: ^4.8.0
  json_serializable: ^6.6.0
  logger: ^1.1.0
  metadata_god: ^0.3.2
  mime: ^1.0.2
  package_info_plus: ^3.0.2
  palette_generator: ^0.3.3
  path: ^1.8.0
  path_provider: ^2.0.8
  permission_handler: ^10.2.0
  pocketbase: ^0.7.1+1
  popover: ^0.2.6+3
  queue: ^3.1.0+1
  scroll_to_index: ^3.0.1
  shared_preferences: ^2.0.11
  sidebarx: ^0.15.0
  simple_circular_progress_bar: ^1.0.2
  skeleton_text: ^3.0.0
  spotify:
    git:
      url: https://github.com/rinukkusu/spotify-dart
      ref: 9e8ef4556942d42d74874de5491253156e7e6f43
  system_theme: ^2.1.0
  titlebar_buttons: ^1.0.0
  tuple: ^2.0.1
  url_launcher: ^6.1.7
  uuid: ^3.0.7
  version: ^3.0.2
  visibility_detector: ^0.3.3
  window_manager: ^0.3.1
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      ref: a738913c8ce2c9f47515382d40827e794a334274
      path: plugins/window_size
  youtube_explode_dart: ^1.12.1

dev_dependencies:
  build_runner: ^2.3.2
  flutter_distributor: ^0.0.2
  flutter_gen_runner: ^5.1.0+1
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  pub_api_client: ^2.4.0
  pubspec_parse: ^1.2.2

dependency_overrides:
  package_info_plus: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/tutorial/
    - .env
    - LICENSE

flutter_icons:
  android: true
  image_path: "assets/spotube-logo.png"
  adaptive_icon_foreground: "assets/spotube-logo-foreground.jpg"
  adaptive_icon_background: "#242832"
  windows:
    generate: true
    image_path: "assets/spotube-logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/spotube-logo.png"

flutter_gen:
  output: lib/collections
  integrations:
    flutter_svg: true
